apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "xg/f5VxKVCXuDUQFJ55xGEeHHk9F9g2cfUIpeTzhEg28psLBz9Jiguoj4atAJxJl\n+f6qy2KdU3Jx42/l7wSy5mc9BlqA0stTE8aGhK318kq2D5+pnZUE/ysm+oJNA2XR\njXrvUbAs7MswVXynoI+zZYhSxE+m2GWdlz1Z88kV7c0="
